### ISSUE TITLE
Editor fails to build

### ISSUE THREAD

**Issue by TrevorCash** [rokups/Urho3D#21]
Using the Following Cmake Configuration with Visual Studio 2017 (Commit: 5017f6453ba4fce667160604d1003b626018a784):
--   Runtime         SHARED
--   Library         STATIC
--   SSE             ON
--   2D              ON
--   IK              ON
--   Threading       ON
--   Navigation      ON
--   Network         ON
--   Physics         ON
--   Samples         ON
--   WebP            ON
--   CSharp          OFF
--   MiniDumps       ON
-- Developer options:
--   Packaging       ON
--   SystemUI        ON
--   Logging         ON
--   Profiling       OFF
--   Extras          ON
--   Tools           ON

![image](https://user-images.githubusercontent.com/2559371/43271548-0de2db9a-90b5-11e8-89f2-536cb9c1943d.png)

**Comment by rokups** [comment]
Is this still a problem with latest code on `master`?

**Comment by TrevorCash** [comment]
I'll Test Soon

**Comment by TrevorCash** [comment]
I Get the following errors:
![image](https://user-images.githubusercontent.com/2559371/44961130-ebf20880-aec8-11e8-8ed3-dcb2e4367982.png)

**Comment by rokups** [comment]
https://github.com/rokups/Urho3D/blob/master/Source/Tools/Editor/Assets/AssetConverter.cpp has no reference to `ImportFbx` ¯\\\_(ツ)_/¯

**Comment by TrevorCash** [comment]
pulled master again (non of my changes present) and still does not build after clean build: 
![image](https://user-images.githubusercontent.com/2559371/45853270-8348bf80-bd01-11e8-9abd-2a945da6ea39.png)

**Comment by rokups** [comment]
Try including windows.h in Editor.cpp

**Comment by rokups** [comment]
PR merged, thanks for the fix ;) :+1:
