### ISSUE TITLE
linker errors related to glfw when building with shared third party libs

### ISSUE THREAD

**Issue by TrevorCash** [rokups/Urho3D#22]
With: -DBUILD_SHARED_LIBS=ON On Visual Studio 2017 Building Urho3D Project:
![image](https://user-images.githubusercontent.com/2559371/43861564-738e5cc6-9b14-11e8-81c0-327f4939e3dc.png)

**Comment by rokups** [comment]
Merged single lib work to master. That should solve these issues.
