### ISSUE TITLE
Suggestion: Add GameLauncher Sample to launch 103_GamePlugin sample.

### ISSUE THREAD

**Issue by TrevorCash** [rokups/Urho3D#31]

**Comment by rokups** [comment]
This is still a very WIP thing. I will probably change name of this sample as well. Plan is to make a "player" application. Editor would cook a dump of files (basically some paks + some shared libraries) and player would be able to launch that.

**Comment by rokups** [comment]
We have a `Player` project for a while now. Workflow is something like this:

1. Create a project in editor
2. Enable plugin in the plugins menu
3. Save project
4. Run `Player` application with working directory set to that of a project
