### ISSUE TITLE
3D Gizmo in Local Transform Mode does not rotate with node while simulation is playing.

### ISSUE THREAD

**Issue by TrevorCash** [rokups/Urho3D#37]

**Comment by TrevorCash** [comment]
Towards the end of this video I show it: (note this is from master branch)
https://youtu.be/Xo6i5Q1IZ70

**Comment by rokups** [comment]
Actually this seems to be part of a bigger issue. Playing/stopping scene seems to cause gizmo to get stuck in certain transform space.

**Comment by rokups** [comment]
Fixed in 4da1103d333e59d7a1242c8d7cfb81813e2c4e84
