### ISSUE TITLE
Editor: Reverting Scene State should not reset active camera position as well.

### ISSUE THREAD

**Issue by TrevorCash** [rokups/Urho3D#38]
It seems weird that the camera resets position when exiting play mode.

**Comment by rokups** [comment]
Which camera is that? Scene editor viewport camera does not reset. Game view camera is supposed to reset because it is part of scene state that is restored.

**Comment by rokups** [comment]
I guess you meant editor viewport camera. I later found it does indeed reset and that was fixed.
