### ISSUE TITLE
cr.h on OSX?

### ISSUE THREAD

**Issue by danhambleton** [rokups/Urho3D#41]
Has anyone had any success using cr.h on OSX? From the repo, it sounds like it is doable,  and there actually is an osx branch, but I have not been able to get it working.

**Comment by rokups** [comment]
Probably not. I do not have a mac so i am hardly ever testing anything on this OS. But if you get it working by any chance - both cr.h and this project would love such contribution :)

**Comment by rokups** [comment]
cr.h just received MacOS support. I will update it eventually. Note that this alone is not enough to fully support plugins on MacOS. Most important missing piece is MachO file parsing in [GetPluginType](https://github.com/rokups/Urho3D/blob/master/Source/Tools/Player/Common/PluginUtils.cpp#L221).
