### ISSUE TITLE
Editor Suggestion:  Clicking on node in scene should un-collapse parent nodes in the hierarchy view. 

### ISSUE THREAD

**Issue by TrevorCash** [rokups/Urho3D#44]
When you click on a node in the scene view and the node is a deep child of a parent node, It is hard to find which node the node is in the hierarchy view.  Resulting in seeking through every node in the hierarchy view until you see the one that is highlighted.

It would be nice if the hierarchy view un-collapsed all parent nodes of the selected node automatically.

**Comment by TrevorCash** [comment]
I Made a pr for this: #45

**Comment by rokups** [comment]
PR merged, thank you :)
