### ISSUE TITLE
Editor: Sometimes Right Click Menu will not show up.

### ISSUE THREAD

**Issue by TrevorCash** [rokups/Urho3D#47]
Right now I have not found a way to reproduce it.

**Comment by rokups** [comment]
Could it be that you pressed right button while mouse is moving? That would prevent menu showing up as it is registered as editor camera rotation.

**Comment by TrevorCash** [comment]
No I Remember that once it is in that state - it stays there.  pretty sure I clicked normally after it was in that state.  I think I remember even closing the project and opening a new one - still there.  only thing that fixed it for me was restarting the program.

**Comment by TrevorCash** [comment]
I can get this bug to occur by:

- Opening editor (from visual studio)
- Open Existing Scene
- Right Click Something in the Hierarchy (this works)
- Click the Play Button
- Right Click Something in the Hierarchy (this does not work - probably purposefully?)
- Click the Pause Button
- Right Click Something in the Hierarchy (still does not work)

Seems like something is just not restoring state after the pause button is clicked.

**Comment by rokups** [comment]
This is on purpose. If it is a good idea or not - that is debatable :) Pause button does not stop scene simulation, just pauses it so you can do single step simulation if need be. Play (and thus read-only) state is indicated by dimming non-scene tabs.
